/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from protobuf

package org.apache.drill.exec.proto.beans;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class PushDataRequestHeader implements Externalizable, Message<PushDataRequestHeader>, Schema<PushDataRequestHeader>
{

    public static Schema<PushDataRequestHeader> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static PushDataRequestHeader getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final PushDataRequestHeader DEFAULT_INSTANCE = new PushDataRequestHeader();

    
    private FragmentRecordBatch fragmentRecordBatch;
    private QueryFragmentQuery queryFragmentPlan;

    public PushDataRequestHeader()
    {
        
    }

    // getters and setters

    // fragmentRecordBatch

    public FragmentRecordBatch getFragmentRecordBatch()
    {
        return fragmentRecordBatch;
    }

    public PushDataRequestHeader setFragmentRecordBatch(FragmentRecordBatch fragmentRecordBatch)
    {
        this.fragmentRecordBatch = fragmentRecordBatch;
        return this;
    }

    // queryFragmentPlan

    public QueryFragmentQuery getQueryFragmentPlan()
    {
        return queryFragmentPlan;
    }

    public PushDataRequestHeader setQueryFragmentPlan(QueryFragmentQuery queryFragmentPlan)
    {
        this.queryFragmentPlan = queryFragmentPlan;
        return this;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<PushDataRequestHeader> cachedSchema()
    {
        return DEFAULT_INSTANCE;
    }

    // schema methods

    public PushDataRequestHeader newMessage()
    {
        return new PushDataRequestHeader();
    }

    public Class<PushDataRequestHeader> typeClass()
    {
        return PushDataRequestHeader.class;
    }

    public String messageName()
    {
        return PushDataRequestHeader.class.getSimpleName();
    }

    public String messageFullName()
    {
        return PushDataRequestHeader.class.getName();
    }

    public boolean isInitialized(PushDataRequestHeader message)
    {
        return true;
    }

    public void mergeFrom(Input input, PushDataRequestHeader message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.fragmentRecordBatch = input.mergeObject(message.fragmentRecordBatch, FragmentRecordBatch.getSchema());
                    break;

                case 2:
                    message.queryFragmentPlan = input.mergeObject(message.queryFragmentPlan, QueryFragmentQuery.getSchema());
                    break;

                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, PushDataRequestHeader message) throws IOException
    {
        if(message.fragmentRecordBatch != null)
             output.writeObject(1, message.fragmentRecordBatch, FragmentRecordBatch.getSchema(), false);


        if(message.queryFragmentPlan != null)
             output.writeObject(2, message.queryFragmentPlan, QueryFragmentQuery.getSchema(), false);

    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "fragmentRecordBatch";
            case 2: return "queryFragmentPlan";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("fragmentRecordBatch", 1);
        __fieldMap.put("queryFragmentPlan", 2);
    }
    
}
